### ISSUE TITLE
Support for schemas

### ISSUE THREAD

**Issue by carlos-verdes** [avokka/avokka#4]
I could not find on the code support to setup schemas on a collection.
I think would be a good addition to this library.

**Comment by gbicou** [comment]
no, there is no support for this feature of arangodb.

i'll take a look how to implement this.

**Comment by carlos-verdes** [comment]
ArangoDB does support schemas, I suppose you mean on this library.
Thanks for the quick response! I'm using this library on a REST library based on HTTP4S and Free Monads, I like they way you implemented (AKKA and FS2, generics for the encoders/decoders (I only miss an auto option like Circe but it works good like it is) and the implementation of VPack which I believe improves the ser/deser performance!

Keep it rocking :)

**Comment by gbicou** [comment]
Yes I mean in the library.

The simplest solution is to add schema: VPack to collection parameters, but VPack creation is not intuitive.

If i implement a circe to vpack converter then i can imagine something like : 

```scala
import io.circe.literal._
val schema = json"""
{
  rule: { 
    properties: { nums: { type: "array", items: { type: "number", maximum: 6 } } }, 
    additionalProperties: { type: "string" },
    required: ["nums"]
  },
  level: "moderate",
  message: "The document..."
}
"""

import avokka.velocypack.circe._
collection.create(_.schema(schema.toVPack))
```

I'l add an auto package like the one in circe.

**Comment by gbicou** [comment]
And thanks a lot for the feedback, I appreciate !
